-module(evenfibs).
-export([run/0]).

% Each new term in the Fibonacci sequence is generated by adding the previous two terms.
% By starting with 1 and 2, the first 10 terms will be:

% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

% By considering the terms in the Fibonacci sequence whose values do not exceed four million,
% find the sum of the even-valued terms.

run() -> iterate(1, 2, 0).

iterate(_, _, Sum) when Sum >= 4000000 ->
  io:fwrite("~p~n", [Sum]);
iterate(Last, Next, Sum) when Next rem 2 =:= 0 -> iterate(Next, Last + Next, Sum + Next);
iterate(Last, Next, Sum) -> iterate(Next, Last + Next, Sum).
